name: Enforce Squash Merging into dev

on:
  pull_request:
    branches:
      - development

jobs:
  enforce-squash:
    runs-on: ubuntu-latest

    steps:
      - name: Check Merge Method
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Fetch the pull request details
          PR_DATA=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "${{ github.event.pull_request.url }}")

          # Check if the merge method is set to squash
          MERGE_METHOD=$(echo "$PR_DATA" | jq -r '.mergeable_state')
          if [[ "$MERGE_METHOD" != "clean" ]]; then
            echo "Error: Only squash merges are allowed into dev."
            exit 1
          fi
