name: Merge main into development

on:
  push:
    branches:
      - main

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_FINDER_SECRET }}

      - name: Fetch Current Branch Protection Rules
        id: fetch-protection
        run: |
          curl -s -H "Authorization: token ${{ secrets.GH_FINDER_SECRET }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/branches/development/protection \
            > protection.json
          echo "protection=$(cat protection.json | jq -c .)" >> $GITHUB_ENV

      - name: Allow Merge Commits Temporarily
        run: |
          curl -X PUT -H "Authorization: token ${{ secrets.GH_FINDER_SECRET }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{
              "required_status_checks": null,
              "enforce_admins": true,
              "required_pull_request_reviews": null,
              "restrictions": null,
              "allow_squash_merge": true,
              "allow_merge_commit": true,
              "allow_rebase_merge": false
            }' \
            https://api.github.com/repos/${{ github.repository }}/branches/development/protection

      - name: Merge main into development
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git fetch --all
          git checkout development
          git merge main --allow-unrelated-histories
          git push origin development

      - name: Restore Original Branch Protection Rules
        run: |
          curl -X PUT -H "Authorization: token ${{ secrets.GH_FINDER_SECRET }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d "${{ env.protection }}" \
            https://api.github.com/repos/${{ github.repository }}/branches/development/protection
